### ISSUE TITLE
can you support bitmovin player?

### ISSUE THREAD

**Issue by funnyEagle** [AnonymousMeerkat/inject2download#2]
Thanks

**Comment by AnonymousMeerkat** [comment]
Done! Let me know if it works for the site you want :)

**Comment by funnyEagle** [comment]
Thanks for your quick support, 👍 
but it seems doesn't work for below website 
http://videosws.praegnanz.de/bitmovin/

**Comment by AnonymousMeerkat** [comment]
You're welcome!

It works for me under firefox, but not under chrome. Although I'd love to support chrome just as well as firefox, sadly it doesn't support the "afterscriptexecute" event (which has also sadly been removed from the HTML5 specification), which means that it's basically a race condition (see: https://bugs.chromium.org/p/chromium/issues/detail?id=168175 ).

I think the only way to go around this would be to write an extension for chrome, which I am considering doing at some point :)

**Comment by funnyEagle** [comment]
@AnonymousMeerkat   I tested it under firefox. Yes, the script indeed extracts several links. But they're not the video source link.  Plz take another look. Thanks a lot : )

**Comment by AnonymousMeerkat** [comment]
The video source link is actually either the .mpd file or the .m3u8 file (both should work). From what I understand, they're sort of an index of video and audio parts, it's becoming increasingly common in the internet (youtube, facebook, twitter, etc. use them almost exclusively).

I use youtube-dl to download the video itself, from the .mpd/.m3u8 file (basically it downloads and combines all the parts together), so for the website you linked, it would be:

    youtube-dl 'http://videosws.praegnanz.de/assets/dash/manifest.mpd'

Hopefully this helps :)

**Comment by funnyEagle** [comment]
@AnonymousMeerkat   Thanks : )

 flowplayer also uses this sort of index of video parts, but flowplayer can be cracked into video source path. I'm just wondering if this applies to bitmovin player too.

It seems hard, but I do believe the video should be store somewhere completely.

**Comment by AnonymousMeerkat** [comment]
"the video should be store somewhere completely"

Yes, it could be, but browsers don't need the original mp4 (or whatever other format) file to be able to play the video if they have a .m3u8/.mpd file, and so if any full links are included, it's most likely out of luck :)

But it does seem to be rather common for both the original link and a .m3u8/.mpd link to be included, probably for backwards compatibility. However, in my experience, I find that the .m3u8/.mpd links are, for more websites, more HD than the full .mp4. Although, of course, there's no technical reason for this, but this is probably in order to cater for poor network connections and/or older browsers.

As a sidenote, http://bitmovin.com/hls-mpeg-dash-test-player/ does include the full .mp4, alongside the .m3u8/.mpd :) It really depends on the website.

This being said, I just checked the source of the website you linked, and it appears that I did not implement a wrapper for part of the API (which, incidentally, contains the link to the full, non-segmented video!). I'll get to implementing this ASAP :)

**Comment by funnyEagle** [comment]
Thank you so much!  👍     
I feel I need to learn some JS now.  Oh btw, after I downloaded the video, I found the audio part is missing

**Comment by AnonymousMeerkat** [comment]
You're welcome! I just committed an update which adds the full URLs. I believe this should cover almost all cases (from _actually_ reading the API documentation this time), but of course, let me know if you run across any issues :)

**Comment by funnyEagle** [comment]
@AnonymousMeerkat 
plz check this page, I try to download the tech talk form this website. But it still doesn't work. As you said, it really depends on websites.   
https://www.bittiger.io/classpage/8FkPjjSZM46LNFjN5

I tried to use youtube-dl,  it can only download the video part, audio part is missing
Thanks a lot.

**Comment by AnonymousMeerkat** [comment]
I tried:

    youtube-dl --no-check-certificate 'https://cdn-v6.tianmaying.com/bitmovin/564033_a520cbd81c99cbf0e6351e9b66f70040/564033.m3u8'

And it worked fine for me (video has audio). Maybe there's a problem with the .mpd file?

I haven't tried downloading the .mpd file, simply because it takes a really long time haha. However, I tried with the URL you provided above (http://videosws.praegnanz.de/bitmovin/), and both the .mpd and the .m3u8 files had audio.

Have you tried updating youtube-dl and ffmpeg maybe?

I reuploaded the video you linked to mega, with audio: https://mega.nz/#!gW5UELjT!dKRoekR9SzoezXEU6s0hXZ0HPO9PIpEHr_tGHt9K_do

**Comment by funnyEagle** [comment]
Wow, thanks so much.  Are you able to find the source video path for this website?

**Comment by AnonymousMeerkat** [comment]
You're very welcome! And yes, https://cdn-v6.tianmaying.com/bitmovin/564033_a520cbd81c99cbf0e6351e9b66f70040/564033.m3u8 (part of the `youtube-dl` command I linked in the last post).

I wonder why audio doesn't work on your side though... Here's the output I get when downloading the .mpd and .m3u8 files from the videosws site:

```
$ youtube-dl 'http://videosws.praegnanz.de/assets/dash/manifest.mpd'
[generic] manifest: Requesting header                                                                                                                                                                               
WARNING: Falling back on generic information extractor.                                                                                                                                                             
[generic] manifest: Downloading webpage                                                                                                                                                                             
[generic] manifest: Extracting information                                                                                                                                                                          
[download] Destination: manifest-manifest.fmanifest-5.webm                                                                                                                                                          
[download] 100% of 7.01MiB in 00:20                                                                                                                                                                                 
[download] Destination: manifest-manifest.fmanifest-6.webm                                                                                                                                                          
[download] 100% of 586.83KiB in 00:02                                                                                                                                                                               
[ffmpeg] Merging formats into "manifest-manifest.webm"                                                                                                                                                              
Deleting original file manifest-manifest.fmanifest-5.webm (pass -k to keep)                                                                                                                                         
Deleting original file manifest-manifest.fmanifest-6.webm (pass -k to keep)
```

```
$ youtube-dl 'http://videosws.praegnanz.de/assets/hls/master.m3u8'
[generic] master: Requesting header
[generic] master: Downloading m3u8 information
[download] Destination: master-master.mp4
ffmpeg version 3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.1 (GCC) 20170306
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-lib
ass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenj
peg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enab
le-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-netcdf --enable-shared --enable-version3
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, hls,applehttp, from 'http://videosws.praegnanz.de/assets/hls/video_1920x1080_2500k.m3u8':
  Duration: 00:00:37.80, start: 1.437333, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:master-master.mp4.part':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  947 fps= 14 q=-1.0 Lsize=   22621kB time=00:00:37.90 bitrate=4888.3kbits/s speed=0.561x
video:22014kB audio:593kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.061401%
[ffmpeg] Downloaded 23163851 bytes
[download] 100% of 22.09MiB
```

Does your output look similar?

Specifically, in the first one, do you see two `Destination: manifest-manifest.[...]` lines, and the `Merging formats into [...]` line, and in the second, do you see `Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp`?

**Comment by funnyEagle** [comment]
Oh, i mean the complete mp4 source file.  

Yeah, it works for me on http://videosws.praegnanz.de.  But, it don't work on 564033_a520cbd81c99cbf0e6351e9b66f70040/564033.m3u8. 
It took me about an hour to download the best quality version video.. I guess the video part and audio part are separated?

**Comment by AnonymousMeerkat** [comment]
Oh, no, sorry, I simply downloaded the .m3u8 I linked above via youtube-dl, which converted it to a .mp4, and then I uploaded that to mega :)

Hmm interesting. Well I'll see what happens if I download the .mpd file, since I haven't tried that (due to the fact that it also took me about an hour to download it haha).

And yes, video and audio are separated, but they _should_ be put back together by youtube-dl...

**Comment by funnyEagle** [comment]
let me try m3u8 file. Thanks.
But you figure out the source mp4 file for first website< http://videosws.praegnanz.de/bitmovin/>, no way to figure out the second one?

**Comment by funnyEagle** [comment]
Also I tried `youtube-dl --no-check-certificate 'https://cdn-v6.tianmaying.com/bitmovin/564033_a520cbd81c99cbf0e6351e9b66f70040/564033.m3u8'`
it shows 'requested format not available' 
That's why i tired add -f option on my own cmd.

**Comment by AnonymousMeerkat** [comment]
The first website was because I didn't read the API documentation properly haha. I'll look into the second one a bit more in case I missed something, but according to the documentation of bitmovin, a full video file (.mp4 etc.) is not at all required, and will actually only be used as a fallback, if everything else fails.

Hmm, it didn't give me that error ... are you sure you're on the latest version of youtube-dl? I'm on 2017.05.07 currently.

**Comment by funnyEagle** [comment]
It works now. Something went wrong with my ffmpeg.  Thanks for your time. It would be really helpful if you could find it out.

**Comment by AnonymousMeerkat** [comment]
You're welcome! So after looking into it, from what I can see, the .m3u8 and the .mpd files are all that can be gathered from the site, unfortunately.

**Comment by funnyEagle** [comment]
Okay. NP.  Btw how long did u take to download the video?  Why it took so long on my side?

**Comment by AnonymousMeerkat** [comment]
It probably took me about an hour as well (or felt like it at least haha). I'm guessing the server is either slow for foreign connections, or intentionally throttles bandwidth because it thinks that we're watching the video in realtime, as opposed to downloading (in which case, it doesn't need to have a very high speed, and in fact, giving a very high speed could cause the service to be less fast for other users).
